name: Live Cricket Score Scraper

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install selenium webdriver-manager beautifulsoup4 pytz

      - name: Run Scraper
        run: python test.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json README.md
          git commit -m "Updated live match data and README [$(date)]" || echo "No changes to commit"
          git push
